name: Github Actions로 테스트 자동화하기

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        with:
          node-version: 22
          # cache 제거! (중요)

      - name: pnpm 설치하기
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 테스트 실행하기
        run: pnpm test
