name: Preview 배포

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        with:
          node-version: 22
          # cache 제거! (중요)

      - name: pnpm 설치하기
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 테스트 실행하기
        run: pnpm test

      - name: Vercel CLI 설치
        run: npm install --global vercel@latest

      - name: Vercel 환경 정보 가져오기
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: 프로젝트 빌드
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel에 프로젝트 배포
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
